@startuml
title Handling Article Scraping in NewsOnTheGo

create ":NewsOnTheGo"
activate ":NewsOnTheGo"

 opt Files.exists()

    ' If the file does not exist or is empty
    create ":StorageURL"
    activate ":StorageURL"

    ' NewsOnTheGo requests a list of URLs from StorageURL
    ":NewsOnTheGo" -> ":StorageURL" : getURLs()
    ":StorageURL" --> ":NewsOnTheGo" : List<String> URLs
    destroy ":StorageURL"

    ' Create an instance of ArticleScraper for scraping articles
    create ":ArticleScraper"

    ' Loop through each URL in the list and scrape articles
    loop for each URL
        ":NewsOnTheGo" -> ":ArticleScraper" : scrapeArticle(url, outputDirectoryPath)
    end
    destroy ":ArticleScraper"

end

deactivate ":NewsOnTheGo"
@enduml
