@startuml

class DailyNewsCommand {
- {static}articlesOfTheDay : List<NewsArticle>

 + DailyNewsCommand(input : String, list : List<NewsArticle>)
 + {static}save(input : String[]) : void
 - {static}saveDailyArticlesParser() : void
}

@enduml