@startuml
'https://plantuml.com/sequence-diagram
actor User

-> NewsOnTheGo: main()
activate NewsOnTheGo
NewsOnTheGo-> "NewsFile:savedNews": NewsFile()
activate "NewsFile:savedNews"

User->NewsOnTheGo : "clear"

NewsOnTheGo->NewsOnTheGo: ProcessCommand("clear")
activate NewsOnTheGo

NewsOnTheGo->Parser: handleCommand("clear")
activate Parser

Parser->NewsOnTheGo: clearSavedNews()
deactivate Parser
destroy Parser
activate NewsOnTheGo
NewsOnTheGo->"NewsFile:savedNews": clearFile()

"NewsFile:savedNews"-->NewsOnTheGo



NewsOnTheGo->NewsOnTheGo: false
note left
false return signals to
continue to poll for user input
end note
deactivate NewsOnTheGo


@enduml