
@startuml
'https://plantuml.com/sequence-diagram

activate Parser
alt Command == FILTER
Parser->NewsOnTheGo: filterNews()
activate NewsOnTheGo
NewsOnTheGo->NewsOnTheGo: findTopicIndex()
activate NewsOnTheGo
NewsOnTheGo-->NewsOnTheGo: topicIndex
deactivate NewsOnTheGo
NewsOnTheGo-->Parser: topicIndex
deactivate NewsOnTheGo
destroy NewsOnTheGo
end

alt Command == SAVE
alt topicIndex >= 0
Parser->NewsFile: saveNews(filteredList)
activate NewsFile
NewsFile-->Parser
deactivate NewsFile
destroy NewsFile
else topicIndex = -1
Parser->NewsFile: saveNews(mainList)
activate NewsFile
NewsFile-->Parser
deactivate NewsFile
destroy NewsFile
end
end
destroy Parser
@enduml